ur5:
  wrist1_position_controller:
    type: position_controllers/JointPositionController
    joint: wrist_1_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  wrist2_position_controller:
    type: position_controllers/JointPositionController
    joint: wrist_2_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  wrist3_position_controller:
    type: position_controllers/JointPositionController
    joint: wrist_3_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  shoulder_lift_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: shoulder_lift_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  shoulder_pan_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: shoulder_pan_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  elbow_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: elbow_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
